#!/usr/bin/env python

Import('env')
Import('env_modules')

env_midi = env_modules.Clone()

# Thirdparty source files
# Not unbundled for now as they are not commonly available as shared library
thirdparty_dir = "#thirdparty/rtmidi/"
thirdparty_sources = [ "RtMidi.cpp" ]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_midi.add_source_files(env.modules_sources, thirdparty_sources)
env_midi.Append(CPPPATH=[thirdparty_dir])

# Godot's own source files
env_midi.add_source_files(env.modules_sources, "*.cpp")
env_midi.Append(CPPDEFINES = ['__WINDOWS_MM__'])
env_midi.Append(LIBS=["winmm"])
#

#Import('env')

#sources = [
#  "register_types.cpp",
  #"summator.cpp",
  #"midi_in.cpp",
  #"midi_out.cpp"
#]

#module_env = env.Clone()
#module_env.Append(CXXFLAGS=['-O2', '-std=c++11'])

#if ARGUMENTS.get('summator_shared', 'no') == 'yes':
#  module_env.Append(CXXFLAGS='-fPIC')
#  module_env['LIBS'] = []

  # how to add third party? :\
#  thirdparty_dir = "#thirdparty/rtmidi/"
#  thirdparty_sources = [
#    "RtMidi.cpp",
#  ]
#  thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]
#  module_env.add_source_files(env.modules_sources, thirdparty_sources)
#  module_env.Append(CPPPATH=[thirdparty_dir])

  # how to add platform specific stuff?
#  module_env.Append(CPPDEFINES = ['__WINDOWS_MM__'])
#  module_env.Append(LIBS=["winmm"])

#  shared_lib = module_env.SharedLibrary(target="#bin/summator", sources=sources)
#  shared_lib_shim = shared_lib[0].name.rsplit('.', 1)[0]
#  env.Append(LIBS=[shared_lib_shim])
#  env.Append(LIBPATH=['#bin'])
#else:
  # Static comilation
  # Thirdparty source files
  # Not unbundled for now as they are not commonly available as shared library
#  thirdparty_dir = "#thirdparty/rtmidi/"
#  thirdparty_sources = [
#      "RtMidi.cpp",
#  ]
#  thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

#  module_env.add_source_files(env.modules_sources, thirdparty_sources)
#  module_env.Append(CPPPATH=[thirdparty_dir])

  # Godot's own source files
#  module_env.add_source_files(env.modules_sources, "*.cpp")

  # how to add platform specific stuff?
#  module_env.Append(CPPDEFINES = ['__WINDOWS_MM__'])
#  module_env.Append(LIBS=["winmm"])
